### ISSUE TITLE
Section groupings

### ISSUE THREAD

**Issue by brandur** [brandur/microservices#15]
Here's my pitch for section groups. Some of these are a little arbitrary, so I'm more than okay with changes.

* Introduction
    * Terminology
    * Practice Moderation
* Service Design
    * Share Data, Not A Database
    * Ensure Correctness With Atomicity
    * Deploy Discretely
    * Be Resilient
    * Be A Good Citizen _(not yet written)_ ["Be Social"?]
    * Pool Connections
* API Design
    * Enforce Strong Contracts
    * Execute Idempotently
    * Stream State Changes
* Platform Design
    * Instrument, Observe, and Correlate
    * Normalize Practices
    * Defend In Depth

Notes:

* I'm still not super happy with "API Design".
* I think both "consider the log" and "pool connections" aren't quite up to spec with some of the others. We might want to either rename these to be more general or more aspirational.
* "Idempotency Is The Key" doesn't fit the start-with-verb pattern. I guess I missed it.

cc @tt

**Comment by brandur** [comment]
I think "Consider The Log" could conceivably be replaced with "Practice Economy" that suggests preferring efficient state streaming over "chatty" Webhooks (or KPI) style APIs.

**Comment by tt** [comment]
I don't have a solid answer but here is an alternative approach organising around some of the main values (which would be great to define if not grouped like this):

- Introduction
  - Terminology
  - Practice Moderation
- Isolation
  - Share Data, Not A Database
  - Deploy Discretely
- Composition
  - Enforce Strong Contracts
  - Ensure Correctness With Atomicity
  - Execute Idempotently
  - Stream State Changes
  - Defend In Depth
- Reliability/robustness
  - Be Resilient
  - Be A Good Citizen (not yet written) ["Be Social"?]
  - Pool Connections
- Consistency/operability
  - Instrument, Observe, and Correlate
  - Normalize Practices

**Comment by brandur** [comment]
> (which would be great to define if not grouped like this):

Hah yeah, feel free to take a shot at that separately. It would be a useful exercise.

I like that organization. A few notes:

* "Reliability/robustness" -> "Resilience"?
* "Consistency/operability" -> "Operation"?
* I think "Defend In Depth" could go to "Reliability/robustness".
* I think "Normalize Practices" has a somewhat contrived placement. It might belong in its own category like "Organization" or something.
* A few sections seem out of place in their category: "Be A Good Citizen", "Pool Connections".

**Comment by brandur** [comment]
Renamed "Idempotency Is The Key" ["Use Idempotency", "Use Idempotent Endpoints"?] to "Execute Idempotently" in 4fce2ee. Updating the comments above.

**Comment by brandur** [comment]
Renamed Consider The Log ["Stream State Changes"?] to "Stream State Changes" in 73bf422. Updating the comments above.
