### ISSUE TITLE
Suggest terminology

### ISSUE THREAD

**Issue by tt** [brandur/microservices#4]
Is there any well-established terminology?

If not, I think a *service* is made up of *components*. Each *component* can itself be a *service* with a number of *components*. The principles would generally apply between *components* and only within the same *service*.

(A number of *services* together is a *platform*.)

**Comment by brandur** [comment]
> Is there any well-established terminology?

Hm, good question. Check out this section in Fowler's article [1]. I think he's using _component_ to mean a modular piece of a _software system_ (read "The key property of a component is the notion of independent replacement and upgradeability"). I believe that a _component_ may be a _service_ (at which point it's deployed and operated independently), but could also be a simple submodule of its parent system.

Is that basically consistent with how you were thinking about it?

I do think that we should put in an introductory section that includes a "A Note On Terminology" section in it. I've basically been using all these terms nearly interchangeably and I'm probably not the only one who considers most of them synonyms in practice.

[1] http://www.martinfowler.com/articles/microservices.html#EvolutionaryDesign

**Comment by brandur** [comment]
Thinking about this some more, I kind of like the word "platform" as opposed to "software system". The word's a bit overloaded, but "software system" is just as vague, and more sterile.
