### ISSUE TITLE
New section: Rate limits

### ISSUE THREAD

**Issue by brandur** [brandur/microservices#6]
A new section that says something along the lines of:

> Enforce rate limits for resource access, even internally between services. Make sure that services can tolerate being rate limited and back off while another system recovers, preferably with minimal user impact. The greater a system's scale, the more likely a "thundering herd" event is to eventually occur where one service clobbers another.

Thoughts @tt?

**Comment by tt** [comment]
Sounds good!

I would maybe make the broader advice "Be Good Citizens" and include things such as respecting existing standards (HTTP, ISO 8601, UTC, UTF-8 etc.), apply reliability patterns (hereunder do exponential back off not only when rate limited) and (maybe) invoke Postel's law. I'm not entirely sure if this even belongs anywhere, though.

**Comment by tt** [comment]
I'm trying to think about how to ultimately structure everything but Chaos Monkey could deserve a mention if there should be practices to complement the theory.

**Comment by tt** [comment]
The more I think about it, Postel's law should probably be cited as a thing to avoid within a service boundary to ensure quality.

**Comment by brandur** [comment]
@tt So I like the "be good citizens" piece. I was originally trying to suggest almost the inverse to this though — i.e. that services should defend themselves to some degree by rate limiting. I wonder if along with that former section we could have one for "Build Hardened Services" (not super happy with this name) that describes rate limiting and how network degradation should be expected to happen. The Chaos Monkey could be mentioned there as a way to test that defense.

**Comment by tt** [comment]
I totally agree that components need to also defend themselves but the point of "[making] sure that services can tolerate being rate limited" felt like it belonged in the other category. Maybe "Tolerate Failures" would be a good name?

**Comment by brandur** [comment]
Another point for the "be good citizens" section: introduce jitter.

**Comment by brandur** [comment]
Done in #17.
