### ISSUE TITLE
New section: Actionable failures

### ISSUE THREAD

**Issue by brandur** [brandur/microservices#7]
A new section that goes something along the lines of:

> Failures within the greater platform should have a clear owner who can be actioned with their resolution. For example, when writing something like an integration test, it's not enough to know that the test failed, it must clearly be able to identify _where_ it failed.

Sorry for the PR wave @tt, but thoughts on that one?

**Comment by tt** [comment]
In my unsaved buffer, I had named this "Correlation" and mandated that components must assign a `Request-ID`* and provide a `User-Agent` (or comparable) to allow tracing and blaming.

*) This probably deserves a mention of best practices too: Generate an ID internally and prepend that to the value of the incoming request. Use the internal ID for most log entries but pass on the aggregated value for outbound requests.

**Comment by brandur** [comment]
+1. How about "Observe & Correlate" as a section name? I'll tackle it tomorrow.
