### ISSUE TITLE
New sections

### ISSUE THREAD

**Issue by brandur** [brandur/microservices#8]
@tt Just opening this as a general stub for you to draft out any new sections that you might have ideas for. I brainstormed the seed collection quite quickly and am a little afraid that I missed some important things in there.

**Comment by tt** [comment]
In the twelve-factor app, "there is always a one-to-one correlation between the codebase and the app". I think there is a significant number of people doing microservices who use a single repository and I do think it can encourage consistency but I'm not sure whether it belongs here. What do you think?

**Comment by brandur** [comment]
@tt Man, I'm still waffling on that one.

We do the monorepo thing. It's kind of nice because it allows you to commit broad refactors more easily and when you establish a new convention or tool you only need to do it one place (take adding in a Linter for example). When someone makes an improvement, everyone gets it, and it's harder for any one team to start building a new localized and exotic thing.

But to be honest, it's also not great. The repo has enough throughput that it's pretty much impossible for one person to watch every incoming PR. You might say that this is an anti-pattern, but by extension it also means that no one can really help ensure overall code quality or help shepherd the shape of its overall design. A very nefarious form of tragedy of the commons type situation sets in. The edit-compile-debug cycle becomes C++-level slow, test quality/speed really suffers and eventually you _need_ CI to run the entire suite; doing anything locally is a total non-starter. Everything gets really fragile. After you get to a _huge_ number of commits even basic Git operations start to get really slow.

I'm still undecided and would probably lean toward just not talking about it here :)

**Comment by brandur** [comment]
Closing this one down for now.
